<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Sheherjan" failures="1" tests="1" name="Default test" time="44.944" errors="0" timestamp="2024-01-28T12:24:40 BDT">
  <testcase classname="com.tutorialsninja.qa.testcases.register" name="verifyRegisteringAnAccountWithoutAllDetails" time="2.632">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.lang.CharSequence.toString()&amp;quot; because &amp;quot;s&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
at java.base/java.lang.String.contains(String.java:2862)
at com.tutorialsninja.qa.pages.RegisterPage.displayStatusOfWarningMessages(RegisterPage.java:167)
at com.tutorialsninja.qa.testcases.register.verifyRegisteringAnAccountWithoutAllDetails(register.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRegisteringAnAccountWithoutAllDetails -->
  <testcase classname="com.tutorialsninja.qa.testcases.register" name="verifyRegisteringAnAccountWithAllFields" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAnAccountWithAllFields -->
  <testcase classname="com.tutorialsninja.qa.testcases.register" name="verifyRegisteringAnAccountWithMandatoryFields" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAnAccountWithMandatoryFields -->
  <testcase classname="com.tutorialsninja.qa.testcases.register" name="verifyRegisteringAnAccountWithExistingEmailAddress" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisteringAnAccountWithExistingEmailAddress -->
</testsuite> <!-- Default test -->
